#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely
#   With a sleep 2 and I am invincible!!! when receiving a SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done